### ISSUE TITLE
Adjust `AutoReqProv` in spec file.

### ISSUE THREAD

**Issue by seenteage** [bbc/speculate#10]
Hello,

thanks for this nice project.
I need to configure `AutoReqProv` in my project.
Some dependencies I use have python files in them.
This adds python libraries as dependencies to my node project.
Therefore I want to disable `AutoReqProv`.

It's not too important as I'm currently using sed (`sed -i '/AutoReq: no/a AutoReqProv: no' SPECS/live-channels.spec`) to add this line to the spec file.

Regards

**Comment by robinjmurphy** [comment]
Hi @seenteage. Thanks for the feedback. I need to do a little reading on this option but we can certainly look at adding it for you.

**Comment by robinjmurphy** [comment]
Hi @seenteage. Would it work for you if we set both `AutoReq` and `AutoReqProv` to `no`?

I'm not too sure on the difference between them, but our original aim was to simply disable all automatic requiring.

**Comment by robinjmurphy** [comment]
Just to update you @seentage - I'm going to switch out `AutoReq` for `AutoReqProv`. PR here: https://github.com/bbc/speculate/pull/11.

**Comment by seenteage** [comment]
thank you!
