### ISSUE TITLE
building RPM

### ISSUE THREAD

**Issue by lukejpreston** [bbc/speculate#27]
if I am using speculate what would you recommend for building the RPM

I am using

`rpmbuild --define \"_topdir `pwd`\" -ba SPECS/my-project.spec`

I am using cosmos docker container so can use anything. Just wondering what would be work with this?

**Comment by njh** [comment]
I am personally using ```mock-build --os 7```, but it isn't publicly available.

Available from the [otg-build-tools](https://repository.api.bbci.co.uk/otg-build-tools/) RPM repo and in this GitHub repo:
https://github.com/bbc/bbc-mock-tools

Mocking is a bit slow but it is does do it nicely.

**Comment by niklasR** [comment]
We're using an internal tool too. I have emailed you, but for anyone else interested, search Confluence for 'speculate' and it's the first link.

**Comment by robinjmurphy** [comment]
I actually started a guide for doing this with just `rpmbuild` (completely non-BBC-ified). https://gist.github.com/robinjmurphy/f815050a451e173a153d. I'm not sure why I never added it to the project :-/. Might be worth publishing it somewhere?

**Comment by niklasR** [comment]
Ouh great, thanks @robinjmurphy, we'll look into it next week!

**Comment by lukejpreston** [comment]
thanks, I am looking over all these things now
