### ISSUE TITLE
Do not escape output in %post

### ISSUE THREAD

**Issue by Limess** [bbc/speculate#32]
When including scripts including special characters such as `"` Handlebars will escape them, resulting in `&quot;` which breaks.

Example command;

```js
"post": [
    ...
    "find /etc/bake-scripts/application -maxdepth 1 -type f ! \\( -name \"*.pyc\" -or -name \"*.pyo\" \\) -exec chmod +x {} +"
]
```

outputs 
```
%post
...
find /etc/bake-scripts/application -maxdepth 1 -type f ! \( -name &quot;*.pyc&quot; -or -name &quot;*.pyo&quot; \) -exec chmod +x {} +
```

Just needs to use `{{{`, see http://handlebarsjs.com/#html-escaping.

**Comment by DaMouse404** [comment]
I think we had a similar request before, quite happy to merge a PR 😄

**Comment by njh** [comment]
I had this problem too. I worked round it by not using characters that get escaped 😒
