### ISSUE TITLE
Executables in spec template

### ISSUE THREAD

**Issue by lindy-topcoder** [bbc/speculate#36]
The current template adds multiple `defattrs` for each executable. According to the [specs](http://ftp.rpm.org/max-rpm/s1-rpm-inside-files-list-directives.html) i think it should be something more like:

```
%files
%defattr(644, {{username}}, {{username}}, 755)
/usr/lib/{{name}}
/var/log/{{name}}
{{#hasExecutableFiles}}
{{#executableFiles}}
%attr(755, {{username}}, {{username}}) {{.}}
{{/executableFiles}}
{{/hasExecutableFiles}}
```

giving each executable 755 permissions, otherwise you'd get `Unable to create immutable header region` errors.

**Comment by DaMouse404** [comment]
Hi @lindy-topcoder, 

I'm not sure I understand, the output for that section looks something along these lines:
https://github.com/bbc/speculate/blob/master/test/fixtures/my-cool-api-with-executable.spec#L44-L50

So one `%defattr` heading for the multiple files specified. I've also tested this with one of our services which has multiple executable files and we are not seeing the error you describe. Could you please expand further?

**Comment by lindy-topcoder** [comment]
this is the simplest package.json i could get to fail.

```
{
  "name": "rpmbuild-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "spec": "speculate"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel-cli": "^6.24.1",
    "webpack": "^3.4.1"
  },
  "spec": {
    "executable": [
      "./node_modules/webpack/bin/webpack.js",
      "./node_modules/babel-cli/bin/babel.js"
    ]
  },
  "devDependencies": {
    "speculate": "^1.7.2",
    "webpack-dev-server": "^2.6.1"
  }
}
```

fails with

```
RPM build errors:
    File listed twice: /usr/lib/rpmbuild-test/node_modules/babel-cli/bin/babel.js
    File listed twice: /usr/lib/rpmbuild-test/node_modules/webpack/bin/webpack.js
    Unable to create immutable header region.
```

changing the template as i mentioned above works as expected.

**Comment by DaMouse404** [comment]
Hi @lindy-topcoder, 

I tested the above `package.json` under CentOS 7 and it worked fine for me. Can you advise as to what platform you're attempting to build on?

**Comment by lindy-topcoder** [comment]
centos/7 in vagrant with rpmbuild version 4.11.3

**Comment by DaMouse404** [comment]
Hi @lindy-topcoder,

I can't seem to replicate this issue using that template, the only difference I can imagine is a different version of NPM inside of the RPM build or similar influence. I think it's probably best to submit a PR and I will test to see if it impacts any of our existing services?

**Comment by lindy-topcoder** [comment]
submitted #37 #

**Comment by DaMouse404** [comment]
Hi @lindy-topcoder, I've just published this release. Could you verify it's working as expected?

**Comment by DaMouse404** [comment]
I'm going to assume this now works as intended 😸. Feel free to reopen if needed.
