### ISSUE TITLE
License isn't set after building the RPM

### ISSUE THREAD

**Issue by napindc** [bbc/speculate#38]
After I run the "npm run spec" command, which in the package.json, has:

`scripts: { spec: "speculate"`

It generates a .spec file in the SPECS folder. Looking into that file, the "License: " is blank. So when I run a "rpmbuild -bb SPECS/<spec_file.spec>", the error I get is:

`error: Macro %version has empty body
error: line 12: Empty tag: License:`

I can manually go into the spec file, edit it, and enter in a license, but I dont' want to do that all the time. The license needs to get automatically generated.

**Comment by AlexChesters** [comment]
@napindc does your `package.json` have an entry in the `license` field?

**Comment by napindc** [comment]
Oh that was it, thanks!

**Comment by napindc** [comment]
Also curious - is there a way to have a dynamic "version" at all? Right now I have to manually enter that into the spec file. I'm trying to see if I can the entire RPM process over some continuous integration tool (like Jenkins), and doing it there I might not be able to manually enter in the version #.

**Comment by DaMouse404** [comment]
Hi @napindc,

You can use the `--release` flag from within Jenkins similar to this:
```
"spec": "speculate --release $BUILD_NUMBER"
```

**Comment by napindc** [comment]
Doesn't that only affect the "release" though? I have 
`"spec": "speculate --release 3"`

and that creates:

`%define version
%define release 3`

And thus I need to manually edit it and enter in the version.

**Comment by DaMouse404** [comment]
So you can set the version to a fixed value and the release is appended to it. So if you have `version` as `1.0.0` and then use the `$BUILD_NUMBER` it'll version like this:

`1.0.0-${BUILD_NUMBER}`

**Comment by napindc** [comment]
The issue I'm having though is that whenever I run the "npm run spec" command, the version is blank. I have not yet run this from jenkins (I'm still doing it from the command line) ... but even from the command line I have to go into the spec file and manually enter in the version.

If `"spec": "speculate --version 1.0.0 --release 3"` worked, then that would be ideal, for example.

**Comment by AlexChesters** [comment]
@napindc I believe the version comes from the `version` field in your `package.json`. Is that set to something?

**Comment by napindc** [comment]
Well duh... thanks. Did that and now it's working.
