### ISSUE TITLE
Possibility to override post steps (no systemctl)

### ISSUE THREAD

**Issue by tobiaslins** [bbc/speculate#41]
We would like to use this tool to create the spec files for our projects.

The problem is that we don't want to use the systemctl feature because we want to run the services with systemctl. We would like to use PM2 for the process management because it gives us features such as clustering.

Would it be possible to create a flag to disable the post action `systemctl enable`

I could also create a PR for that

Thanks

**Comment by DaMouse404** [comment]
Hi @tobiaslins,

Is it not possible to build the PM2 startup into the `npm start` script? We use both `cluster` and `systemd` to manage failure of our service at either the `master` or `worker` level. One of the key goals of `speculate` is to enable us to install and run software as RPM based services as fast as possible, I'm not sure removing the `systemd` section even if configurable meets that goal.

Cheers,
Chris

**Comment by tobiaslins** [comment]
Thank you @DaMouse404 !
Do you have any static deploys (react app etc)
If yes:
Do you also deploy these with RPM packages? 

Cheers,
Tobi

**Comment by DaMouse404** [comment]
Hi @tobiaslins, 

We do have static asset deployments but not typically through RPMs. They just get uploaded to some storage and then served from there in a versioned folder, preferably behind some kind of CDN.

Cheers,
Chris
