### ISSUE TITLE
wtf, npm prune --production is removing packages in dependencies ?

### ISSUE THREAD

**Issue by Jayflux** [bbc/speculate#42]
Trying to build this with speculate https://github.com/bbc/sounds-performance/blob/master/package.json
"express" is in the dependencies block, however after `npm prune --production` runs im left with....

```
[developer@sounds-performance sounds-performance]$ ls node_modules/
chrome-launcher  cross-spawn  lighthouse  normalize-package-data  package-json  redent  registry-auth-token  registry-url  semver-diff  send  yargs
```

It removes express, even though its not in devDependencies
Is this some weird NPM 5.0.0 issue??

**Comment by DaMouse404** [comment]
It appears to be working correctly as far as my quick testing goes:

```
$ ls node_modules/ | grep express
express
spdx-expression-parse
$ npm prune --production
removed 20 packages in 1.277s
$ ls node_modules/ | grep express
express
spdx-expression-parse
$ npm --version
5.5.1
```

What version of npm are you using?

**Comment by Jayflux** [comment]
5.0.0

**Comment by DaMouse404** [comment]
We had a load of issues with the initial release of npm 5.x so I'd suggest you try updating it and see if the issue persists.

**Comment by DaMouse404** [comment]
Closing this as it hasn't been touched in awhile.

**Comment by Jayflux** [comment]
@DaMouse404  its worth noting this is still a problem (even on Node 8.9.1) we've just got round it by not pruning anything.

This isn't really sustainable, so we'll either need to find a version of NPM that works (i'm not really up for rolling back Node/NPM as an option), or being able to swap in yarn

**Comment by AlexChesters** [comment]
This thread is rather old but I thought I'd just confirm that this is indeed a bug in NPM.

https://github.com/npm/npm/issues/19356
