### ISSUE TITLE
Configurable start script

### ISSUE THREAD

**Issue by jtart** [bbc/speculate#50]
Currently speculate expects the start script to be `npm start`.

While in most cases this is fine, it might be useful to have this configurable.

A minor improvement.

**Comment by njh** [comment]
Hi,

Are there any examples of how this would be useful?
What would be started if not the thing configured to start when running `npm start`?

There are lots of features that _could_ be added to speculate - but at some point it is easier just to create an RPM spec file.

nick.

**Comment by njh** [comment]
Closing this as there has been no further communication.

Please re-open if there is more to say about this.

**Comment by emansom** [comment]
We're using PM2 in production and would like the systemd service file to execute PM2 directly instead of wrapping it through NPM

**Comment by njh** [comment]
What is the disadvantage of it being wrapped by npm?
