### ISSUE TITLE
Configurable Unit options to the service file

### ISSUE THREAD

**Issue by dantailby** [bbc/speculate#52]
Hey,

I was wondering if you would consider allowing configuration of the `[Unit]` block within the generate service file, to go along with the already configurable `[Service]` options.

My app needs to specify custom options for `Before`, `After` and `Requires` to ensure it starts properly.

I have a branch ready with the necessary changes if you're happy to take a look.

Really nice tool btw! 👍

**Comment by DaMouse404** [comment]
@dantailby, PRs are always welcome 😸I think this is a useful feature for a lot of people.

**Comment by dantailby** [comment]
@DaMouse404 Great, I've raised a PR: https://github.com/bbc/speculate/pull/53

**Comment by DaMouse404** [comment]
@dantailby this should be available in `2.0.0-alpha.3`

**Comment by dantailby** [comment]
Fantastic, thanks!
