### ISSUE TITLE
Recommended way to get bake-scripts into /etc/bake-scripts?

### ISSUE THREAD

**Issue by keir-lavelle** [bbc/speculate#62]
Hi there, 

I'm trying to get the bake-scripts from my repository in place into /etc/bake-scripts. I tried adding a `mv` command into the post array in my package.json, but I just repeatedly get an error that 'mkdir: cannot create directory ‘/mnt/bertinet-f/etc/bake-scripts’: File exists'
Even though I'm not firing an mkdir command anywhere, which is really confusing. 

I'm just wondering if theres' a prescriptive way to get the bake-scripts in place so that they'll be executed?

**Comment by DaMouse404** [comment]
That is odd, we've done this before with:

```
  "spec": {
    "executable": [
      "./bake-scripts/1-cake.js"
    ],
    "post": [
      "mv /usr/lib/my-cake-service/bake-scripts /etc/bake-scripts/my-cake-service"
    ]
  }
```

**Comment by keir-lavelle** [comment]
I think it may be some permissions issue, I can create a directory inside /etc/bake-scripts and mv the scripts into there, and they get executed as expected - the problem only seems to be trying to move them into /etc/bake-scripts top level. Thanks for your help on this 👍
