### ISSUE TITLE
Moving off alpha - v2.0.0

### ISSUE THREAD

**Issue by UsainBloot** [bbc/speculate#67]
I have noticed that we have been running v2.0.0 alphas for several months now.

Is there anything currently blocking us to move away from v2 alphas?

Would be good to list out exactly what needs to be addressed before we can move onto standard releases.

**Comment by njh** [comment]
I am personally unsure why we are on alpha - is there a lack of confidence in the new versions?
I think we should get off alpha and then fix any problems that are reported.

And maybe get my PRs merged 😉

**Comment by DaMouse404** [comment]
Alpha was primarily whilst building and testing the whitelist capabilities, I believe this has been battle tested enough to roll out a proper `2.0.0`. We should look at any remaining PRs and prioritise any further breaking changes before releasing `2.0.0`.

**Comment by UsainBloot** [comment]
Moved off alpha - https://github.com/bbc/speculate/releases/tag/v2.0.0
