### ISSUE TITLE
Feature request: Ability to exclude files/directories from the archive

### ISSUE THREAD

**Issue by fewstera** [bbc/speculate#8]
Thanks for the great tool.

It would be great if it was possible to exclude files from being added to the source archive.

**Comment by robinjmurphy** [comment]
This sounds like a good feature. Is this something you'd be up for contributing? We can try and pick it up soon if not.

Should be easy to do as we already ignore some files https://github.com/bbc/speculate/blob/master/lib/archiver.js#L9-L11.

**Comment by fewstera** [comment]
We can pick this up. I'll submit a PR when I get time 👍

**Comment by lukejpreston** [comment]
I am having a look at doing this now

it currently uses regex `var IGNORE_REGEX = /SOURCES|SPECS|RPMS|SRPMS|\.git/;`

should it extend this in the `package.json` with a value like

```json
"spec": {
  "exclude": ["pattern_1", "pattern_2" ...] || "regex_pattern"
}
```

or did you guys have something else in mind?

**Comment by Jayflux** [comment]
Lets not make it too magic, a simple `excludes:[]` is all we need for now.
Then we'll have to try and extend the IGNORE_REGEX or have something similar

**Comment by DaMouse404** [comment]
I think it'd be nicer to have `package.json` work as normally as possible, the `spec` section should really be for things we can't achieve easily with a normal `package.json` file.  

Given that, I think we'd only have to implement `directories` and maybe `files` to start with as a generic "add these things to the RPM" for any of the given keys and see if there's anything further people want afterwards?

PRs always welcome 😸

**Comment by lukejpreston** [comment]
I am a fan of project config being put into the package.json, things like eslint, jest and webpack do this and it feels natural and nice

That said I haven't pursued it any further, the project I was working that was using this got canned and I don't have time to look into it
